## 通用文件上传
ha-oos:
  ## 七牛云
  qiniu:
    domain: #七牛云绑定的域名
    access-key: #七牛云ACCESS_KEY
    secret-key: #七牛云SECRET_KEY
    bucketname: #七牛云存储空间名
    prefix: #路径前缀
    enable: false #是否启用
  ## 阿里云
  ali:
    domain:  #阿里云绑定的域名
    end-point: #阿里云EndPoint
    access-key-id: #阿里云AccessKeyId
    access-key-secret: #阿里云AccessKeySecret
    bucketname: #阿里云BucketName
    prefix: #路径前缀
    enable: false #是否启用
  ## 腾讯云
  tencent:
    domain: #腾讯云绑定的域名
    app-id: #腾讯云AppId
    secret-id: #腾讯云SecretId
    secret-key: #腾讯云SecretKey
    bucketname:  #腾讯云BucketName
    region:  #腾讯云COS所属地区
    prefix: #路径前缀
    block: false #是否分块上传 简单上传的方式只支持最大5GB的文件上传，而通过分块上传的方式可上传大于5GB的文件
    enable: false #是否启用
  ## FastDFS
  fastdfs:
    domain: #FastDFS绑定的域名
    enable: false #是否启用
  ## 本地上传
  local:
    domain: #本地上传绑定的域名
    path: #本地上传存储目录
    prefix: #路径前缀
    enable: false #是否启用
  ## Minio
  minio:
    end-point: #Minio EndPoint
    access-key: #Minio accessKey
    secret-key: #Minio secretKey
    bucket-name: #Minio BucketName
    prefix: #路径前缀
    enable: false #是否启用
